/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "on-surface": "#ffdedb",
        "secondary-fixed": "#91f78e",
        "surface": "#240303",
        "surface-container-highest": "#491311",
        "on-tertiary-fixed-variant": "#681f7a",
        "on-tertiary-fixed": "#400050",
        "tertiary-container": "#ef9dff",
        "error-container": "#9f0519",
        "on-surface-variant": "#de9a94",
        "primary-fixed": "#ff7949",
        "on-tertiary": "#68207b",
        "on-primary": "#591700",
        "inverse-surface": "#fff8f7",
        "on-error-container": "#ffa8a3",
        "surface-bright": "#521816",
        "on-primary-container": "#451000",
        "tertiary-dim": "#e190f1",
        "outline": "#a16661",
        "on-secondary-fixed": "#00480f",
        "on-primary-fixed": "#000000",
        "outline-variant": "#6c3a36",
        "error": "#ff716c",
        "tertiary-fixed-dim": "#e190f1",
        "background": "#240303",
        "on-primary-fixed-variant": "#551600",
        "secondary-dim": "#83e881",
        "surface-dim": "#240303",
        "secondary": "#91f78e",
        "tertiary-fixed": "#ef9dff",
        "on-secondary": "#005e17",
        "secondary-container": "#006e1c",
        "error-dim": "#d7383b",
        "on-secondary-fixed-variant": "#00691a",
        "inverse-on-surface": "#7c4642",
        "surface-variant": "#491311",
        "on-error": "#490006",
        "surface-container-low": "#2c0505",
        "surface-tint": "#ff906a",
        "on-background": "#ffdedb",
        "inverse-primary": "#ac3500",
        "primary-fixed-dim": "#f7652f",
        "surface-container-high": "#3f0e0d",
        "primary-container": "#ff7949",
        "surface-container": "#360909",
        "secondary-fixed-dim": "#83e881",
        "on-secondary-container": "#e5ffde",
        "primary": "#ff906a",
        "tertiary": "#f5b2ff",
        "on-tertiary-container": "#5e1470",
        "primary-dim": "#ff7442"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Be Vietnam Pro"]
      },
      borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
    },
  },
  plugins: [],
}
